# Generated by Django 3.2 on 2021-06-03 12:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('paradox', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='team',
        ),
    ]
