# Generated by Django 3.2 on 2021-06-03 12:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('paradox', '0003_alter_user_detail_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_detail',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='details', to=settings.AUTH_USER_MODEL),
        ),
    ]
