# Generated by Django 3.2 on 2021-06-03 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paradox', '0005_auto_20210603_2026'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='id',
        ),
        migrations.AlterField(
            model_name='question',
            name='level',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
