# Generated by Django 3.2 on 2021-06-04 11:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('paradox', '0008_auto_20210604_1727'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team_member',
            name='beta',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='beta', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='team_member',
            name='gamma',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='gamma', to=settings.AUTH_USER_MODEL),
        ),
    ]
